apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: area-tech-tls
  namespace: deployment
spec:
  secretName: area-tech-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - registry.tech.aether-area.fr
    - argocd.tech.aether-area.fr
    - phpmyadmin.tech.aether-area.fr
    - api.aether-area.fr
    - aether-area.fr
