query getAppletNodeById($id: Int!) {
    getAppletNodeById(id: $id) {
        id
        actionId
        actionType
        input
        provider {
            id
            name
            color
            img
        }
        next {
            id
        }
    }
}
