fragment ProviderWithManifest on Provider {
    ...BaseProvider
    manifest {
        actions {
            ...ProviderManifestAction
        }
        triggers {
            ...ProviderManifestTrigger
        }
    }
}
