name: aether-provider-name
namespace: deployment

deployment:
  replicas: 1
  resources:
    limits:
      memory: "512Mi"
      cpu: "1000m"
    requests:
      memory: "256Mi"
      cpu: "500m"
  ports:
    - containerPort: 3001
  env: []

service:
  type: ClusterIP
  port: 80
  targetPort: 3001
  restartPolicy: Always

image:
  repository: registry.tech.aether-area.fr/b-dev-500_area_name
  tag: latest
  pullPolicy: Always
  pullSecrets:
    name: regcred