name: aether-api
namespace: deployment

deployment:
  replicas: 1
  resources:
    limits:
      memory: "512Mi"
      cpu: "550m"
    requests:
      memory: "256Mi"
      cpu: "500m"
  ports:
    - containerPort: 3000
  env: []

service:
  type: ClusterIP
  port: 443
  portLocal: 80
  targetPort: 3000
  restartPolicy: Always

image:
  repository: registry.tech.aether-area.fr/b-dev-500_area_server
  tag: latest
  pullPolicy: Always
  pullSecrets:
    name: regcred