version: "3.8"

services:
  provider:
    image: node:22-alpine
    build:
      context: ../..
    ports:
      - 6001:6001
    working_dir: /app
    volumes:
      - ../../:/app
    command: yarn serve-nest
