apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      name: traefik
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.2
          args:
            - --providers.kubernetesingress
            - --api.insecure
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
            - name: dashboard
              containerPort: 8080
              protocol: TCP
      restartPolicy: Always
