apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: traefik-web
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
  type: LoadBalancer
