# targets:
#   $default:
#     builders:
#       gql_build|schema_builder:
#         enabled: true
#       gql_build|ast_builder:
#         enabled: true
#       gql_build|data_builder:
#         enabled: true
#         options:
#           schema: mobile|lib/graphql/auth.graphql
#       gql_build|var_builder:
#         enabled: true
#         options:
#           schema: mobile|lib/graphql/auth.graphql
#       gql_build|serializer_builder:
#         enabled: true
#         options:
#           schema: mobile|lib/graphql/auth.graphql
#       ferry_generator|req_builder:
#         enabled: true
#         options:
#           schema: mobile|lib/graphql/auth.graphql
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: aether|lib/graphql/schema.graphql

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: aether|lib/graphql/schema.graphql

      json_serializable:
        options:
          explicit_to_json: true