name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  ferry: 0.16.0+1
  gql_http_link: ^1.1.0
  gql: ^1.0.0+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  gql_build: ^0.11.0+1
  ferry_generator: ^0.10.0
  build_runner: ^2.3.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
