name: aether
description: "Aether AREA project"

version: 1.0.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  ferry: 0.16.0+1
  ferry_flutter: ^0.9.1-dev.1
  gql_http_link: ^1.1.0
  gql: ^1.0.0+1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_secure_storage: ^8.0.0
  webview_flutter: ^4.2.1
  test: ^1.25.7
  gql_error_link: ^1.0.0+1
  gql_transform_link: ^1.0.0
  built_collection: ^5.1.1
  gql_exec: ^1.0.0+1
  gql_link: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  gql_build: ^0.11.0+1
  ferry_generator: ^0.10.0
  build_runner: ^2.3.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Italic.ttf
          style: italic