services:
  api:
    image: node:22-alpine
    build:
      context: ../..
    ports:
      - "8080:3000"
    depends_on:
      - mariadb
    working_dir: /app
    volumes:
      - ../../:/app
    command: yarn serve-nest

  mariadb:
    image: mariadb:11.5.2
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ${DATA_PATH_HOST}mariadb/mariadb_data:/var/lib/mysql
      - ${DATA_PATH_HOST}mariadb/database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mariadb


  provider-discord:
    image: node:22-alpine
    build:
      context: ../../../providers/discord
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ../../../providers/discord:/app
    command: yarn serve-nest
