query getProviderById($id: Int!) {
    getProviderById(id: $id) {
        id
        name
        description
        img
        color
        visibility
        manifest {
            actions {
                id
                name
                description
                img
                color
                input
                output
            }
            triggers {
                id
                name
                description
                img
                color
                input
                output
            }
        }
    }
}
