services:
  microsoft:
    image: node:22-alpine
    build:
      context: ../..
    ports:
      - "3005:3005"
    working_dir: /app
    volumes:
      - ../../:/app
    networks:
      - area-api
    command: yarn serve-nest

networks:
  area-api:
    name: area_api
    external: true
