name: Push CI/CD

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - 'ga-ignore-**'
  push:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-DEV-500-PAR-5-2-area-matteo.emile.git"

jobs:
  push:
    name: Build & Tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=10g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'yarn'
      - name: Run tests
        run: "yarn install && yarn test:unit"
#      - name: Build
#        run: "docker-compose --env-file .env.example build"
#        timeout-minutes: 10

  push_to_mirror:
    name: "Pushing To The Mirror Repository"
    runs-on: ubuntu-latest

    needs: push
    if: github.event.repository.name != 'B-DEV-500-PAR-5-2-area-matteo.emile.git'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}